services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - ./migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/000001_init_schema.up.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_PWD}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mediasoft-task

  statistics:
    build:
      context: .
      dockerfile: Dockerfile
    image: mediasoft-statistics
    depends_on:
      restaurant_db:
        condition: service_healthy
    ports:
      - "8004:8004"
      - "8005:8005"
    networks:
      - mediasoft-task

networks:
  mediasoft-task:
    external: true